name: "Check Lychee Version and Create PR"

on:
  schedule:
    - cron: "0 0 * * 0" # every Sunday
  workflow_dispatch:

jobs:
  check-lychee-version:
    runs-on: ubuntu-latest

    outputs:
      mismatch: ${{ steps.compare-versions.outputs.mismatch }}
      action_lychee_version: ${{ steps.get-action-lychee-version.outputs.action_lychee_version }}
      release_version: ${{ steps.get-lychee-release.outputs.release_version }}

    name: Check lychee version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current lychee release version
        id: get-lychee-release
        run: |
          echo "Fetching the latest lychee release version..."
          release=$(curl -s https://api.github.com/repos/lycheeverse/lychee/releases/latest | jq -r .tag_name)
          release=${release#lychee-} # Strip the 'lychee-' prefix
          echo "Latest release version fetched: $release"
          echo "release_version=$release" >> $GITHUB_OUTPUT

      - name: Extract lycheeVersion from action.yml
        id: get-action-lychee-version
        run: |
          echo "Extracting lycheeVersion from action.yml..."
          lychee_version=$(grep -Po '(?<=lycheeVersion:\s*default:\s*)v[0-9.]+' action.yml)
          if [ -z "$lychee_version" ]; then
            echo "Error: Failed to extract lycheeVersion from action.yml"
            exit 1
          fi
          echo "Extracted lycheeVersion: $lychee_version"
          echo "action_lychee_version=$lychee_version" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare-versions
        run: |
          echo "Comparing versions..."
          echo "Action lychee version: $action_lychee_version"
          echo "Latest release version: $release_version"
          if [ "$action_lychee_version" != "$release_version" ]; then
            echo "Versions do not match. Setting mismatch to true."
            echo "mismatch=true" >> $GITHUB_OUTPUT
          else
            echo "Versions match. Setting mismatch to false."
            echo "mismatch=false" >> $GITHUB_OUTPUT
          fi

  create-pr:
    needs: check-lychee-version
    runs-on: ubuntu-latest
    if: needs.check-lychee-version.outputs.mismatch == 'true'

    name: Create PR to update lychee version
    env:
      action_lychee_version: ${{ needs.check-lychee-version.outputs.action_lychee_version }}
      release_version: ${{ needs.check-lychee-version.outputs.release_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create branch for update
        run: |
          echo "Creating a new branch for the update..."
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b update-lychee-version
          echo "Updating action.yml with the new lychee version..."
          sed -i "s/$action_lychee_version/$release_version/" action.yml
          git commit -am "Update lycheeVersion to $release_version"
          echo "Pushing the branch to the repository..."
          git push origin update-lychee-version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-lychee-version
          title: "Update lycheeVersion to $release_version"
          body: "This PR updates the lycheeVersion to the latest release version $release_version."
          labels: "automated pr"
          assignees: arteiii
